FROM node:22-alpine

# 1. DevSecOps: Patch underlying Alpine OS vulnerabilities
RUN apk update && apk upgrade --no-cache

# 2. Set production environment
ENV NODE_ENV=production
WORKDIR /app

# 3. Copy manifests and install ONLY production dependencies
COPY --chown=node:node package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

# 4. Copy the compiled SvelteKit server generated by adapter-node
COPY --chown=node:node build/ ./build/
COPY --chown=node:node package.json ./

# 5. DevSecOps: Remove NPM to eliminate Trivy vulnerabilities
RUN rm -rf /usr/local/lib/node_modules/npm /usr/local/bin/npm /usr/local/bin/npx

USER node
EXPOSE 3000

# 6. Execute the raw Node server directly (Bypassing NPM)
CMD ["node", "build/index.js"]